services:
  test-db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db

  user-service:
    build: ./user_service
    environment:
      DATABASE_URL: postgresql://test_user:test_password@test-db:5432/test_db
    depends_on:
      - test-db
    ports:
      - "8001:8000"