# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: post.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'post.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npost.proto\x12\x04post\"m\n\x11\x43reatePostRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x12\n\ncreator_id\x18\x03 \x01(\x05\x12\x12\n\nis_private\x18\x04 \x01(\x08\x12\x0c\n\x04tags\x18\x05 \x03(\t\"{\n\x11UpdatePostRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x12\n\nis_private\x18\x04 \x01(\x08\x12\x0c\n\x04tags\x18\x05 \x03(\t\x12\x14\n\x0crequestor_id\x18\x06 \x01(\x05\"\x1c\n\x0eGetPostRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"5\n\x11\x44\x65letePostRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0crequestor_id\x18\x02 \x01(\x05\"V\n\x10ListPostsRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x0c\n\x04size\x18\x02 \x01(\x05\x12\x17\n\ncreator_id\x18\x03 \x01(\x05H\x00\x88\x01\x01\x42\r\n\x0b_creator_id\"\x9c\x01\n\x0cPostResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x12\n\ncreator_id\x18\x04 \x01(\x05\x12\x12\n\ncreated_at\x18\x05 \x01(\t\x12\x12\n\nupdated_at\x18\x06 \x01(\t\x12\x12\n\nis_private\x18\x07 \x01(\x08\x12\x0c\n\x04tags\x18\x08 \x03(\t\"E\n\x11ListPostsResponse\x12!\n\x05posts\x18\x01 \x03(\x0b\x32\x12.post.PostResponse\x12\r\n\x05total\x18\x02 \x01(\x05\"\x0f\n\rEmptyResponse2\xb6\x02\n\x0bPostService\x12\x39\n\nCreatePost\x12\x17.post.CreatePostRequest\x1a\x12.post.PostResponse\x12\x37\n\x0bGetPostById\x12\x14.post.GetPostRequest\x1a\x12.post.PostResponse\x12\x39\n\nUpdatePost\x12\x17.post.UpdatePostRequest\x1a\x12.post.PostResponse\x12:\n\nDeletePost\x12\x17.post.DeletePostRequest\x1a\x13.post.EmptyResponse\x12<\n\tListPosts\x12\x16.post.ListPostsRequest\x1a\x17.post.ListPostsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'post_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEPOSTREQUEST']._serialized_start=20
  _globals['_CREATEPOSTREQUEST']._serialized_end=129
  _globals['_UPDATEPOSTREQUEST']._serialized_start=131
  _globals['_UPDATEPOSTREQUEST']._serialized_end=254
  _globals['_GETPOSTREQUEST']._serialized_start=256
  _globals['_GETPOSTREQUEST']._serialized_end=284
  _globals['_DELETEPOSTREQUEST']._serialized_start=286
  _globals['_DELETEPOSTREQUEST']._serialized_end=339
  _globals['_LISTPOSTSREQUEST']._serialized_start=341
  _globals['_LISTPOSTSREQUEST']._serialized_end=427
  _globals['_POSTRESPONSE']._serialized_start=430
  _globals['_POSTRESPONSE']._serialized_end=586
  _globals['_LISTPOSTSRESPONSE']._serialized_start=588
  _globals['_LISTPOSTSRESPONSE']._serialized_end=657
  _globals['_EMPTYRESPONSE']._serialized_start=659
  _globals['_EMPTYRESPONSE']._serialized_end=674
  _globals['_POSTSERVICE']._serialized_start=677
  _globals['_POSTSERVICE']._serialized_end=987
# @@protoc_insertion_point(module_scope)
