# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import api_gateway_app.stats_grpc.stats_pb2 as stats__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in stats_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StatsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPostStats = channel.unary_unary(
                '/stats.StatsService/GetPostStats',
                request_serializer=stats__pb2.PostIdRequest.SerializeToString,
                response_deserializer=stats__pb2.PostStatSummary.FromString,
                _registered_method=True)
        self.GetPostViewsByDay = channel.unary_unary(
                '/stats.StatsService/GetPostViewsByDay',
                request_serializer=stats__pb2.PostIdRequest.SerializeToString,
                response_deserializer=stats__pb2.DailyStatResponse.FromString,
                _registered_method=True)
        self.GetPostLikesByDay = channel.unary_unary(
                '/stats.StatsService/GetPostLikesByDay',
                request_serializer=stats__pb2.PostIdRequest.SerializeToString,
                response_deserializer=stats__pb2.DailyStatResponse.FromString,
                _registered_method=True)
        self.GetPostCommentsByDay = channel.unary_unary(
                '/stats.StatsService/GetPostCommentsByDay',
                request_serializer=stats__pb2.PostIdRequest.SerializeToString,
                response_deserializer=stats__pb2.DailyStatResponse.FromString,
                _registered_method=True)
        self.GetTopPostsBy = channel.unary_unary(
                '/stats.StatsService/GetTopPostsBy',
                request_serializer=stats__pb2.TopRequest.SerializeToString,
                response_deserializer=stats__pb2.TopItemsResponse.FromString,
                _registered_method=True)
        self.GetTopUsersBy = channel.unary_unary(
                '/stats.StatsService/GetTopUsersBy',
                request_serializer=stats__pb2.TopRequest.SerializeToString,
                response_deserializer=stats__pb2.TopItemsResponse.FromString,
                _registered_method=True)


class StatsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPostStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPostViewsByDay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPostLikesByDay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPostCommentsByDay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopPostsBy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopUsersBy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPostStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostStats,
                    request_deserializer=stats__pb2.PostIdRequest.FromString,
                    response_serializer=stats__pb2.PostStatSummary.SerializeToString,
            ),
            'GetPostViewsByDay': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostViewsByDay,
                    request_deserializer=stats__pb2.PostIdRequest.FromString,
                    response_serializer=stats__pb2.DailyStatResponse.SerializeToString,
            ),
            'GetPostLikesByDay': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostLikesByDay,
                    request_deserializer=stats__pb2.PostIdRequest.FromString,
                    response_serializer=stats__pb2.DailyStatResponse.SerializeToString,
            ),
            'GetPostCommentsByDay': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostCommentsByDay,
                    request_deserializer=stats__pb2.PostIdRequest.FromString,
                    response_serializer=stats__pb2.DailyStatResponse.SerializeToString,
            ),
            'GetTopPostsBy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopPostsBy,
                    request_deserializer=stats__pb2.TopRequest.FromString,
                    response_serializer=stats__pb2.TopItemsResponse.SerializeToString,
            ),
            'GetTopUsersBy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopUsersBy,
                    request_deserializer=stats__pb2.TopRequest.FromString,
                    response_serializer=stats__pb2.TopItemsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stats.StatsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stats.StatsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StatsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPostStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stats.StatsService/GetPostStats',
            stats__pb2.PostIdRequest.SerializeToString,
            stats__pb2.PostStatSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPostViewsByDay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stats.StatsService/GetPostViewsByDay',
            stats__pb2.PostIdRequest.SerializeToString,
            stats__pb2.DailyStatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPostLikesByDay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stats.StatsService/GetPostLikesByDay',
            stats__pb2.PostIdRequest.SerializeToString,
            stats__pb2.DailyStatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPostCommentsByDay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stats.StatsService/GetPostCommentsByDay',
            stats__pb2.PostIdRequest.SerializeToString,
            stats__pb2.DailyStatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopPostsBy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stats.StatsService/GetTopPostsBy',
            stats__pb2.TopRequest.SerializeToString,
            stats__pb2.TopItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopUsersBy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stats.StatsService/GetTopUsersBy',
            stats__pb2.TopRequest.SerializeToString,
            stats__pb2.TopItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
