# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stats.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'stats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstats.proto\x12\x05stats\" \n\rPostIdRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\x05\"+\n\nTopRequest\x12\x1d\n\x06metric\x18\x01 \x01(\x0e\x32\r.stats.Metric\"A\n\x0fPostStatSummary\x12\r\n\x05views\x18\x01 \x01(\x05\x12\r\n\x05likes\x18\x02 \x01(\x05\x12\x10\n\x08\x63omments\x18\x03 \x01(\x05\"(\n\tDailyStat\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"4\n\x11\x44\x61ilyStatResponse\x12\x1f\n\x05items\x18\x01 \x03(\x0b\x32\x10.stats.DailyStat\"$\n\x07TopItem\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"1\n\x10TopItemsResponse\x12\x1d\n\x05items\x18\x01 \x03(\x0b\x32\x0e.stats.TopItem*)\n\x06Metric\x12\x08\n\x04VIEW\x10\x00\x12\x08\n\x04LIKE\x10\x01\x12\x0b\n\x07\x43OMMENT\x10\x02\x32\x98\x03\n\x0cStatsService\x12<\n\x0cGetPostStats\x12\x14.stats.PostIdRequest\x1a\x16.stats.PostStatSummary\x12\x43\n\x11GetPostViewsByDay\x12\x14.stats.PostIdRequest\x1a\x18.stats.DailyStatResponse\x12\x43\n\x11GetPostLikesByDay\x12\x14.stats.PostIdRequest\x1a\x18.stats.DailyStatResponse\x12\x46\n\x14GetPostCommentsByDay\x12\x14.stats.PostIdRequest\x1a\x18.stats.DailyStatResponse\x12;\n\rGetTopPostsBy\x12\x11.stats.TopRequest\x1a\x17.stats.TopItemsResponse\x12;\n\rGetTopUsersBy\x12\x11.stats.TopRequest\x1a\x17.stats.TopItemsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METRIC']._serialized_start=353
  _globals['_METRIC']._serialized_end=394
  _globals['_POSTIDREQUEST']._serialized_start=22
  _globals['_POSTIDREQUEST']._serialized_end=54
  _globals['_TOPREQUEST']._serialized_start=56
  _globals['_TOPREQUEST']._serialized_end=99
  _globals['_POSTSTATSUMMARY']._serialized_start=101
  _globals['_POSTSTATSUMMARY']._serialized_end=166
  _globals['_DAILYSTAT']._serialized_start=168
  _globals['_DAILYSTAT']._serialized_end=208
  _globals['_DAILYSTATRESPONSE']._serialized_start=210
  _globals['_DAILYSTATRESPONSE']._serialized_end=262
  _globals['_TOPITEM']._serialized_start=264
  _globals['_TOPITEM']._serialized_end=300
  _globals['_TOPITEMSRESPONSE']._serialized_start=302
  _globals['_TOPITEMSRESPONSE']._serialized_end=351
  _globals['_STATSSERVICE']._serialized_start=397
  _globals['_STATSSERVICE']._serialized_end=805
# @@protoc_insertion_point(module_scope)
